name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.AmsterNL }}/Ubuntu-20.04
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.AmsterNL }}
          password: ${{ secrets.dvr_myDbLhljZfs86j0ftAlQBY9BHQojE0uweE3I }}   
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
